### ISSUE TITLE
Working SVG creation spec

### ISSUE THREAD

**Issue by derekr** [diy/icons#1]
We should decide on how to create and export the individual svg files (found in the `svg` directory).

cc @diy/design Let's hash it out in this issue. Add screenshots of export settings and all that jazz.
- What color?
- Consistent sizing/proportions?
- Export settings?

**Comment by rynbrck** [comment]
:+1:

**Comment by derekr** [comment]
@Brocklesocks any update on this? Would be cool to add some notes here this week so I can update the readme.

**Comment by rynbrck** [comment]
I'm a bit tied up in a couple things at the moment, but I can get through it toward the end of the week. Is Thursday or Friday cool to do a walkthrough of the process and documentation?

**Comment by derekr** [comment]
Yeah that's fine – a good start would just be linking to the file in dropbox here and I can start digging through that.

**Comment by rynbrck** [comment]
Here's the icon file and export settings -- it's NOT FINAL, so please don't use these yet!

https://www.dropbox.com/s/oh5ud64cstnj2r1/NOT%20FINAL%20Master%20Icon%20Export%20Sheet.ai?dl=0

![svg export settings](https://cloud.githubusercontent.com/assets/1767966/4650356/e0c1505e-5492-11e4-84e3-573566ca0c1d.jpg)

**Comment by derekr** [comment]
w00t! Thanks dude! I won't throw this in the readme until you have some more time to gather a spec.

**Comment by derekr** [comment]
Icon file https://www.dropbox.com/work/Library%20(1)/-%20Resources/Icons
